### ISSUE TITLE
Timeout due to deadlock that can occure on some threading settings.

### ISSUE THREAD

**Issue by Galigator** [Galigator/openllet#20]
WebOnt-description-logic-905 parse time 0
org.semanticweb.owlapi.reasoner.TimeOutException: Timeout occurred while reasoning!
	at openllet.owlapi.PelletReasoner.convert(PelletReasoner.java:397)
	at openllet.owlapi.PelletReasoner.isConsistent(PelletReasoner.java:1015)
	at openllet.owlwg.runner.pellet.PelletOA3TestRunner.isConsistent(PelletOA3TestRunner.java:50)
	at openllet.owlwg.owlapi.runner.impl.OwlApiAbstractRunner$XConsistencyTest.run(OwlApiAbstractRunner.java:216)
	at openllet.owlwg.runner.pellet.PelletOA3TestRunner.run(PelletOA3TestRunner.java:64)
	at openllet.owlwg.owlapi.runner.impl.OwlApiAbstractRunner.runConsistencyTest(OwlApiAbstractRunner.java:358)
	at openllet.owlwg.owlapi.runner.impl.OwlApiAbstractRunner$Runner.visit(OwlApiAbstractRunner.java:125)
	at openllet.owlwg.owlapi.testcase.impl.OwlApiConTstImpl.accept(OwlApiConTstImpl.java:35)
	at openllet.owlwg.owlapi.runner.impl.OwlApiAbstractRunner$Runner.getResults(OwlApiAbstractRunner.java:117)
	at openllet.owlwg.owlapi.runner.impl.OwlApiAbstractRunner.run(OwlApiAbstractRunner.java:351)
	at openllet.pellet.owlapi.test.OWLWGTestCase.runTestCase(OWLWGTestCase.java:147)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
EXCEPTION [WebOnt-description-logic-905]

**Comment by Galigator** [comment]
If you try to compile openllet (or pellet) and encounter this error you can try 'mvn clean install -DskipTests=true', or try again until it work.
