### ISSUE TITLE
NullPointerException when I get Domain Classes

### ISSUE THREAD

**Issue by renanlf** [Galigator/openllet#22]
Hey Guys,

I have a problem when I use getObjectPropertyDomains from Openllet and my ontology has only properties (no have classes). The Exception is proposital in this case? I expected a empty set or empty stream but no this exception.

Thanks for all!

Follow my trace:

```
java.lang.NullPointerException
	at openllet.core.taxonomy.CDOptimizedTaxonomyBuilder.markToldSubsumers(CDOptimizedTaxonomyBuilder.java:704)
	at openllet.core.taxonomy.CDOptimizedTaxonomyBuilder.doTopSearch(CDOptimizedTaxonomyBuilder.java:972)
	at openllet.core.taxonomy.CDOptimizedTaxonomyBuilder.classify(CDOptimizedTaxonomyBuilder.java:839)
	at openllet.core.taxonomy.CDOptimizedTaxonomyBuilder.classify(CDOptimizedTaxonomyBuilder.java:801)
	at openllet.core.KnowledgeBaseImpl.getAllEquivalentClasses(KnowledgeBaseImpl.java:3971)
	at openllet.core.KnowledgeBaseImpl.getEquivalentClasses(KnowledgeBaseImpl.java:3937)
	at openllet.owlapi.PelletReasoner.getObjectPropertyDomains(PelletReasoner.java:702)
```

**Comment by Galigator** [comment]
What is the version you are using ? This more than one year since there is no code in line 704 of CDOptimizedTaxonomyBuilder.

**Comment by Galigator** [comment]
I can't reproduce it.

**Comment by renanlf** [comment]
Hi,

I'm using version 2.6.1 and I forgot a information. It's occur when I use inverse properties axiom.

Follows a class test

```
public class Test {

	public static void main(String[] args) throws OWLOntologyCreationException {
		OWLOntology ontology = OWLManager.createOWLOntologyManager().createOntology();
		
		OWLObjectProperty a = OWL.ObjectProperty("a");
		OWLObjectProperty b = OWL.ObjectProperty("b");
		
		OWLAxiom inverseAxiom = OWL.inverseProperties(a, b);
		
		ontology.addAxiom(inverseAxiom);
		
		OWLReasoner reasoner = OpenlletReasonerFactory.getInstance().createNonBufferingReasoner(ontology);
		
		NodeSet<OWLClass> clses = reasoner.getObjectPropertyDomains(a);
	}

}
```

**Comment by renanlf** [comment]
I have a new info. If I just declarate a class, the error not happens again.

```
public class Test {

	public static void main(String[] args) throws OWLOntologyCreationException {
		OWLOntology ontology = OWLManager.createOWLOntologyManager().createOntology();
		
		OWLObjectProperty a = OWL.ObjectProperty("a");
		OWLObjectProperty b = OWL.ObjectProperty("b");
		
		OWLAxiom inverseAxiom = OWL.inverseProperties(a, b);
		
		ontology.addAxiom(inverseAxiom);
		ontology.addAxiom(OWL.declaration(OWL.Class("class")));
		
		OWLReasoner reasoner = OpenlletReasonerFactory.getInstance().createNonBufferingReasoner(ontology);
		
		reasoner.getObjectPropertyDomains(a).entities().forEach(
				(cls) -> System.out.println(cls));	
	}

}
```

**Comment by Galigator** [comment]
Thx will watch that.
Look like it is a bug here from long time related to non initialized things.

**Comment by Galigator** [comment]
The error may disappear, but I'm not sure of the correction of result after inserting new axiom that do not use the class.

**Comment by Galigator** [comment]
It was a tricky initialization problem.
Your example is now a test case.
The 2.6.2-SNAPSHOT should work as expected.

**Comment by renanlf** [comment]
Ok, thank you! :)
