### ISSUE TITLE
Unable to initiate 'reasoner' class object of Openllet

### ISSUE THREAD

**Issue by rayaprolu143** [Galigator/openllet#31]
I have used Protege to reason out implicit facts in my ontology. Now, I want to achieve it by simply writing a java code. I loaded the dependencies necessary to run the Openllet reasoner. But, after instantiating a class object, I am presented with the following error:

Exception in thread "main" java.lang.NoSuchMethodError: org.semanticweb.owlapi.model.OWLOntology.importsClosure()Ljava/util/stream/Stream;
	at openllet.owlapi.PelletReasoner.refresh(PelletReasoner.java:1167)
	at openllet.owlapi.PelletReasoner.<init>(PelletReasoner.java:397)
	at openllet.owlapi.PelletReasoner.<init>(PelletReasoner.java:364)
	at openllet.owlapi.OpenlletReasonerFactory.createReasoner(OpenlletReasonerFactory.java:62)
	at com.IITM.SimpleOnto.<init>(SimpleOnto.java:93)
	at CSV2Ontology.main(CSV2Ontology.java:18)

Could you please help me on this issue?

**Comment by Galigator** [comment]
Hello,
to help you I need a little more informations. What version of Openllet are you using ? what version of Java (javac) are you using ?  Do you use maven/gradle ?

**Comment by rayaprolu143** [comment]
Hi,
Thank you for replying. I use maven to install dependencies, version of javac is 1.8.0_151, and finally, the version of Openllet is 2.6.3

**Comment by Galigator** [comment]
Strange. "java/util/stream/Stream" is a Java8 class, not an inner openllet/owl-api class.
How do you execute your code ? Are you sure the execution also use a Java8+ ?

**Comment by rayaprolu143** [comment]
I use intelliJ to execute the code. Does this screenshot serve the purpose?
![screenshot from 2018-02-26 16-23-18](https://user-images.githubusercontent.com/14978999/36666729-865daeca-1b11-11e8-8d50-60309898cd4b.png)

**Comment by ignazio1977** [comment]
It is a classpath problem. You have an incompatible version of OWLAPI in the classpath, one that predates 5.0.0.

**Comment by rayaprolu143** [comment]
But, I am using OWL API 5.1.0, here I am posting my pom file:


[pom.txt](https://github.com/Galigator/openllet/files/1758573/pom.txt)

**Comment by Galigator** [comment]
Ignazio is right, the maven dependency tree show the owlapi-osgidistribution-4.2.8 in the resolved dependencies. It come from swrlapi-2.0.4 . This owlapi-osgidistribution doesn't not conflict with other artifcate because it is the only one to include it; so maven doesn't overwrite the version.

Here you have multiples solutions :

1.   Force include a recent version of owlapi-osgidistribution-5.X.X  ; it may create failure in swrlapi.
2.   Upgrade swrlapi to a version that is using owlapi version 5.X.X

**Comment by rayaprolu143** [comment]
Thanks a lot, Ignazio and Galigator. I modified my pom file according to your suggestions and it worked successfully. Here I am posting the pom file, in case if someone faces a similar issue in future.
[pom.txt](https://github.com/Galigator/openllet/files/1759885/pom.txt)

**Comment by rayaprolu143** [comment]
Although, the previous error vanished it did fail in running SWRL API. Now, I understood where the problem exists, I will try to rectify it by myself or else post the issue separately.

**Comment by ignazio1977** [comment]
The current SWRLAPI is not compatible with OWLAPI 5. I'll put up a forked repo with the required changes.

**Comment by ignazio1977** [comment]
https://github.com/ignazio1977/swrlapi can be checked out and built locally to get SWRLAPI compatible with Openllet and OWLAPI 5. I can't provide a Maven release for this - it would conflict with the Protege provided one, in the long term.

**Comment by rayaprolu143** [comment]
Thank you.

**Comment by rayaprolu143** [comment]
I am presented with the following error:

Exception in thread "main" org.swrlapi.exceptions.SWRLRuleEngineException: Error creating rule engine Drools. Exception: java.lang.NoSuchMethodError. Message: org.semanticweb.owlapi.model.OWLDocumentFormat.isPrefixOWLOntologyFormat()Z
	at org.swrlapi.factory.DefaultSWRLRuleAndQueryEngineFactory.createSWRLRuleEngine(DefaultSWRLRuleAndQueryEngineFactory.java:71)
	at org.swrlapi.factory.DefaultSWRLRuleAndQueryEngineFactory.createSWRLRuleEngine(DefaultSWRLRuleAndQueryEngineFactory.java:41)
	at org.swrlapi.factory.SWRLAPIFactory.createSWRLRuleEngine(SWRLAPIFactory.java:38)
	at SWRLrules.main(SWRLrules.java:57)
Caused by: java.lang.NoSuchMethodError: org.semanticweb.owlapi.model.OWLDocumentFormat.isPrefixOWLOntologyFormat()Z
	at org.swrlapi.factory.DefaultIRIResolver.updatePrefixes(DefaultIRIResolver.java:165)
	at org.swrlapi.factory.DefaultSWRLAPIOWLOntology.<init>(DefaultSWRLAPIOWLOntology.java:163)
	at org.swrlapi.factory.SWRLAPIInternalFactory.createSWRLAPIOntology(SWRLAPIInternalFactory.java:266)
	at org.swrlapi.factory.DefaultSWRLRuleAndQueryEngineFactory.createSWRLRuleEngine(DefaultSWRLRuleAndQueryEngineFactory.java:53)
	... 3 more

I did load the swrl module into the libraries in intellij. I am attaching the screen shot of the libraries in the project, just in case it would be easy for you to verify whether I loaded the modules correctly. 
![screenshot from 2018-02-27 14-27-58](https://user-images.githubusercontent.com/14978999/36719275-a0270518-1bca-11e8-8935-8192773c0309.png)

**Comment by ignazio1977** [comment]
You have swrlapi 2.0.5 still in the classpath. Needs to go and be replaced with the fresh build. Make sure you change the swrlapi version to something different, to ensure intellij cannot get confused.

**Comment by rayaprolu143** [comment]
I am still stuck with the same error. Here I am attaching the screenshot of my libraries:
![screenshot from 2018-02-27 18-18-41](https://user-images.githubusercontent.com/14978999/36729600-c5dd5b70-1bea-11e8-8a39-c38279d2f2bd.png)

I am able to evade the problem when I revert to the previous versions of OWL API distribution with the following pom file:
[pom_works.txt](https://github.com/Galigator/openllet/files/1762695/pom_works.txt)

**Comment by rayaprolu143** [comment]
Hi Ignazio,
I understood where I made the mistake, I removed the maven dependencies for both the swrl api and drools engine and built locally both the dependencies by downloading zip files and used 'mvn install clean' and 'mvn package' and imported them into the project.
