### ISSUE TITLE
InternalReasonerException: Datatype ranges cause exception in backtracking

### ISSUE THREAD

**Issue by greeny277** [Galigator/openllet#32]
Hello.
My ontology has about twenty equivalent classes with datatype ranges, for instance:

```
(concreteDrug some Clozapin)
 and (dose some xsd:integer[>= 100 , <= 250])
```
(I'm using the Protege syntax)

The Openllet reasoner throws me an  **InternalReasonerException** like this:

```
Exception in thread "main" openllet.core.exceptions.InternalReasonerException: Backtrack: Trying to backtrack to _branch 1978 but has only 1970 branches. Clash found: [Clash "anon(25149)" EMPTY_DATATYPE DS{branch:NO_BRANCH(-1), depends:[0, 1969, 1978]} [FunNot(FunRestrictedDatatype(http://www.w3.org/2001/XMLSchema#integer,[FunFacet(http://www.w3.org/2001/XMLSchema#minInclusive,literal(1,(),http://www.w3.org/2001/XMLSchema#integer)),FunFacet(http://www.w3.org/2001/XMLSchema#maxInclusive,literal(4,(),http://www.w3.org/2001/XMLSchema#integer))])), FunNot(FunRestrictedDatatype(http://www.w3.org/2001/XMLSchema#integer,[FunFacet(http://www.w3.org/2001/XMLSchema#minInclusive,literal(2,(),http://www.w3.org/2001/XMLSchema#integer)),FunFacet(http://www.w3.org/2001/XMLSchema#maxInclusive,literal(10,(),http://www.w3.org/2001/XMLSchema#integer))])), FunNot(http://www.w3.org/2001/XMLSchema#integer), FunRestrictedDatatype(http://www.w3.org/2001/XMLSchema#integer,[FunFacet(http://www.w3.org/2001/XMLSchema#minInclusive,literal(60,(),http://www.w3.org/2001/XMLSchema#integer)),FunFacet(http://www.w3.org/2001/XMLSchema#maxInclusive,literal(61,(),http://www.w3.org/2001/XMLSchema#integer))]), http://www.w3.org/2001/XMLSchema#integer]]
        at openllet.core.tableau.completion.SROIQStrategy.backtrack(SROIQStrategy.java:53)
        at openllet.core.rules.ContinuousRulesStrategy.complete(ContinuousRulesStrategy.java:276)
        at openllet.core.boxes.abox.ABoxImpl.isConsistent(ABoxImpl.java:1423)
        at openllet.core.boxes.abox.ABoxImpl.isSatisfiable(ABoxImpl.java:622)
        at openllet.core.boxes.abox.ABoxImpl.isSubClassOf(ABoxImpl.java:567)
        at openllet.core.taxonomy.CDOptimizedTaxonomyBuilder.subsumes(CDOptimizedTaxonomyBuilder.java:1169)
        at openllet.core.taxonomy.CDOptimizedTaxonomyBuilder.subCheckWithCache(CDOptimizedTaxonomyBuilder.java:1127)
        at openllet.core.taxonomy.CDOptimizedTaxonomyBuilder.nodeSubsumes(CDOptimizedTaxonomyBuilder.java:1136)
        at openllet.core.taxonomy.CDOptimizedTaxonomyBuilder.search(CDOptimizedTaxonomyBuilder.java:1051)
        at openllet.core.taxonomy.CDOptimizedTaxonomyBuilder.doTopSearch(CDOptimizedTaxonomyBuilder.java:970)
        at openllet.core.taxonomy.CDOptimizedTaxonomyBuilder.classify(CDOptimizedTaxonomyBuilder.java:834)
        at openllet.core.taxonomy.CDOptimizedTaxonomyBuilder.classify(CDOptimizedTaxonomyBuilder.java:270)
        at openllet.core.taxonomy.CDOptimizedTaxonomyBuilder.classify(CDOptimizedTaxonomyBuilder.java:216)
        at openllet.core.KnowledgeBaseImpl.classify(KnowledgeBaseImpl.java:2360)
        at openllet.core.KnowledgeBaseImpl.realize(KnowledgeBaseImpl.java:2379)
        at openllet.core.KnowledgeBaseImpl.getTypes(KnowledgeBaseImpl.java:3728)
        at openllet.query.sparqldl.engine.CombinedQueryEngine.exec(CombinedQueryEngine.java:360)
        at openllet.query.sparqldl.engine.CombinedQueryEngine.exec(CombinedQueryEngine.java:307)
        at openllet.query.sparqldl.engine.CombinedQueryEngine.exec(CombinedQueryEngine.java:250)
        at openllet.query.sparqldl.engine.QueryEngine.execSingleQuery(QueryEngine.java:330)
        at openllet.query.sparqldl.engine.QueryEngine.exec(QueryEngine.java:127)
        at openllet.query.sparqldl.jena.SparqlDLExecution.exec(SparqlDLExecution.java:241)
        at openllet.query.sparqldl.jena.SparqlDLExecution.execSelect(SparqlDLExecution.java:204)
```

My current Openllet version is 2.6.2. The newer version 2.6.3 fails as well, as does the pellet reasoner version 4.5 used by protege. 

The exact error message differs with each run because it is caused at another place it seems.

For instance:

```
Exception in thread "main" openllet.core.exceptions.InternalReasonerException: Backtrack: Trying to backtrack to _branch 1211 but has only 1192 branches. Clash found: [Clash _C_ ATOMIC DS{branch:NO_BRANCH(-1), depends:[0, 1181, 1182, 1183, 1188, 1194, 1198, 1199, 1201, 1202, 1207, 12
11]}]                                                                             
        at openllet.core.tableau.completion.SROIQStrategy.backtrack(SROIQStrategy.java:53)
        at openllet.core.rules.ContinuousRulesStrategy.complete(ContinuousRulesStrategy.java:276)
        at openllet.core.boxes.abox.ABoxImpl.isConsistent(ABoxImpl.java:1423)     
        at openllet.core.boxes.abox.ABoxImpl.isSatisfiable(ABoxImpl.java:622)           
        at openllet.core.boxes.abox.ABoxImpl.isSubClassOf(ABoxImpl.java:567)              
        at openllet.core.taxonomy.CDOptimizedTaxonomyBuilder.subsumes(CDOptimizedTaxonomyBuilder.java:1169)
        at openllet.core.taxonomy.CDOptimizedTaxonomyBuilder.subCheckWithCache(CDOptimizedTaxonomyBuilder.java:1127)
        at openllet.core.taxonomy.CDOptimizedTaxonomyBuilder.nodeSubsumes(CDOptimizedTaxonomyBuilder.java:1136)
        at openllet.core.taxonomy.CDOptimizedTaxonomyBuilder.search(CDOptimizedTaxonomyBuilder.java:1051)
        at openllet.core.taxonomy.CDOptimizedTaxonomyBuilder.doTopSearch(CDOptimizedTaxonomyBuilder.java:970)
        at openllet.core.taxonomy.CDOptimizedTaxonomyBuilder.classify(CDOptimizedTaxonomyBuilder.java:834)
        at openllet.core.taxonomy.CDOptimizedTaxonomyBuilder.classify(CDOptimizedTaxonomyBuilder.java:270)
        at openllet.core.taxonomy.CDOptimizedTaxonomyBuilder.classify(CDOptimizedTaxonomyBuilder.java:216)
        at openllet.core.KnowledgeBaseImpl.classify(KnowledgeBaseImpl.java:2360)
        at openllet.core.KnowledgeBaseImpl.realize(KnowledgeBaseImpl.java:2379)
        at openllet.core.KnowledgeBaseImpl.getTypes(KnowledgeBaseImpl.java:3728)
        at openllet.query.sparqldl.engine.CombinedQueryEngine.exec(CombinedQueryEngine.java:360)
        at openllet.query.sparqldl.engine.CombinedQueryEngine.exec(CombinedQueryEngine.java:307)
        at openllet.query.sparqldl.engine.CombinedQueryEngine.exec(CombinedQueryEngine.java:250)
        at openllet.query.sparqldl.engine.QueryEngine.execSingleQuery(QueryEngine.java:330)
        at openllet.query.sparqldl.engine.QueryEngine.exec(QueryEngine.java:127)
        at openllet.query.sparqldl.jena.SparqlDLExecution.exec(SparqlDLExecution.java:241)
        at openllet.query.sparqldl.jena.SparqlDLExecution.execSelect(SparqlDLExecution.java:204)

``` 

Yesterday the reasoner was able to successfully finish the reasoning and did then fail again without any changes made in the ontology.
Futhermore I can assure, that these datatype ranges are causing this exception. After removing them, the reasoner works without any issues.

Best regards,
Christian

**Comment by Galigator** [comment]
Interesting, I will try to reproduce.

**Comment by greeny277** [comment]
> Interesting, I will try to reproduce.

Thanks .

If you can't reproduce it I would share my ontology with you.

**Comment by Galigator** [comment]
I failed at reproduce it.

**Comment by greeny277** [comment]
I think I might have found the root of the problem.

When I use two equivalent classes with the same data range limit it crashes although they are not marked as disjoint:

For instance. the following causes a crash:

```
NormalDose = 
(concreteDrug some Clozapin)
 and (dose some xsd:integer[>= 100 , <= 250])

MaximumDose=
(concreteDrug some Clozapin)
 and (dose some xsd:integer[>= 250 , <= 251])

```
When I increase the limit by 1 in the second class, it doesn't fail.

**Comment by greeny277** [comment]
Perhaps you can reproduce this error now.

**Comment by Galigator** [comment]
Okay, even with this information I failed to reproduce the bug. See the test programs [TestBasic.java](https://github.com/Galigator/openllet/blob/integration/module-owlapi/src/test/java/openllet/pellet/owlapi/test/TestBasic.java).

So to show the bug we may use another strategy, I just write a small program that take an ontology that cause a crash/exception and search for a minimal set of axioms that produce the crash/exception; and it rename every entities in it.


This program can be use the following way :
```
git clone https://github.com/Galigator/openllet.git
cd openllet/tools-pellint/
./searchMinimalBug.sh /path/to/the/problematic/ontology/file.owl
```
(it use maven compile then run)

The program  use a random strategy and all yours cpu to search a sub-ontology that create the crash.
The found sub-ontology is put into the file "**minimalOntologyFile.owl**".

The program is 'any-time' (aka it can be stop any time with an ontology that is smaller that your original ontology, once it have check consistency at least one time); because it is random based, you can run it on many computer as you have.

**Comment by greeny277** [comment]
Yet I'm unable to build your project.

For Opennllet Version 2.6.4-SNAPSHOT I get the error:

```
[ERROR] Failed to execute goal on project openllet-pellint: Could not resolve dependencies for project 
com.github.galigator.openllet:openllet-pellint:jar:2.6.4-SNAPSHOT: The following artifacts could not be 
resolved: com.github.galigator.openllet:openllet-jena:jar:2.6.4-SNAPSHOT, 
com.github.galigator.openllet:openllet-owlapi:jar:2.6.4-SNAPSHOT: Could not find artifact 
com.github.galigator.openllet:openllet-jena:jar:2.6.4-SNAPSHOT -> [Help 1]
```

After switching to version 2.6.3 another error occurs:

```

[WARNING]
java.lang.ClassNotFoundException: openllet.pellint.SearchMinimalBug
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:270)
        at java.lang.Thread.run(Thread.java:748)

[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project openllet-pellint: An exception occured while executingthe Java class. openllet.pellint.SearchMinimalBug -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project openllet-pellint: An exception occured while executing the Java class. openllet.pellint.SearchMinimalBug
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: An exception occured while executing the Java class. openllet.pellint.SearchMinimalBug
        at org.codehaus.mojo.exec.ExecJavaMojo.execute(ExecJavaMojo.java:339)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: java.lang.ClassNotFoundException: openllet.pellint.SearchMinimalBug
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:270)
        at java.lang.Thread.run(Thread.java:748)
```

Any suggestions?

**Comment by Galigator** [comment]
The `SearchMinimalBug` is a program I add Saturday morning, so it is only available in the `2.6.4-SNAPSHOT`.

Maybe you need to build the project first.
On the openllet project root  do :

`mvn clean install -DskipTests=true`

before going into tools-pellint/. It should take less than a minute.

**Comment by greeny277** [comment]
Ok [this](https://pastebin.com/xmAHzvUW) is the resulting minimal ontology.

**Comment by greeny277** [comment]
Could you reproduce the error with the minimal ontology?

**Comment by Galigator** [comment]
Sorry for this late answer, I have try your ontology but it look good (didn't throw exception or any crash).
Do you have a configuration file with options for pellet ?

**Comment by greeny277** [comment]
No i don't have any config files for pellet as far as i know...
I also tried reasoning the minimal ontology and i don't get an error either?! This is so weird.
Would you mind trying [this](https://pastebin.com/YAXcH3ym) bigger ontology with SearchMinimalBug.java for a few seconds? Just to see if you get any errors at all.  I tried reasoning the linked ontology as well without removing axioms and it turns out that the randomizeAxioms() functions determines if does crash or not.

**Comment by Galigator** [comment]
Thx for this bigger ontology and for the  analyse on 'randomizeAxioms()'.

I have hack into the ontology and SearchMinimalBug, I can now achieve a 85% bug occurrence on sub-set of your ontology. Baddly this sub set still have more than 1000 axioms.

So I have hack SearchMinimalBug a little more to optimize number of axiom and bug occurrence.

85% is enough to start investigation.

**Comment by greeny277** [comment]
I'm glad that you were able to reproduce the error. I looked up the source code where the error is thrown. These backtracking algorithms are no fun to debug by only staring at the code I can tell. If you will be able to obtain  a smaller ontology feel free to share it so I can help debugging.
Thx for your effort anyway!

**Comment by Galigator** [comment]
The last commit should solve the problem.

There was a problem in the way of backjump when multiple branch are related to clash with dependencies on branch that haven't been explore when backtracking.

The way I resolve it should not mark an inconsistent ontology as consistent, but it may consider inconsistent ontologies that should be consistent if there was any bug.

**Comment by greeny277** [comment]
That sounds great. When will the openllet 2.6.4-SNAPSHOT repository contain this fix so I can try it?

**Comment by greeny277** [comment]
I built the package from the sources and included it into my project. The error hasn't reappeared yet :+1:

**Comment by greeny277** [comment]
Shall I close the issue?

**Comment by Galigator** [comment]
You are welcome.
