### ISSUE TITLE
NullPointerException in rete.JoinCondition.test

### ISSUE THREAD

**Issue by Locke** [Galigator/openllet#39]
Given the code in https://github.com/Locke/pruned_node and the ontology `npe.owl` from that project I get a NullPointerException with this stacktrace:

```
java.lang.NullPointerException
        at openllet.core.rules.rete.JoinCondition.test(JoinCondition.java:29)
        at openllet.core.rules.rete.BetaMemoryNode.testConditions(BetaMemoryNode.java:83)
        at openllet.core.rules.rete.BetaMemoryNode.activate(BetaMemoryNode.java:73)
        at openllet.core.rules.rete.BetaNode.activateChildren(BetaNode.java:28)
        at openllet.core.rules.rete.BetaMemoryNode.activate(BetaMemoryNode.java:74)
        at openllet.core.rules.rete.BetaNode.activateChildren(BetaNode.java:28)
        at openllet.core.rules.rete.BetaMemoryNode.activate(BetaMemoryNode.java:74)
        at openllet.core.rules.rete.BetaNode.activateChildren(BetaNode.java:28)
        at openllet.core.rules.rete.BetaMemoryNode.activate(BetaMemoryNode.java:74)
        at openllet.core.rules.rete.BetaNode.activateChildren(BetaNode.java:28)
        at openllet.core.rules.rete.BetaMemoryNode.activate(BetaMemoryNode.java:74)
        at openllet.core.rules.rete.BetaNode.activateChildren(BetaNode.java:28)
        at openllet.core.rules.rete.BetaMemoryNode.activate(BetaMemoryNode.java:74)
        at openllet.core.rules.rete.BetaNode.activateChildren(BetaNode.java:28)
        at openllet.core.rules.rete.BetaTopNode.activate(BetaTopNode.java:33)
        at openllet.core.rules.rete.AlphaNode.lambda$activate$1(AlphaNode.java:49)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at openllet.core.rules.rete.AlphaNode.activate(AlphaNode.java:49)
        at openllet.core.rules.rete.AlphaTypeNode.activate(AlphaTypeNode.java:60)
        at openllet.core.rules.rete.AlphaNetwork.activateType(AlphaNetwork.java:150)
        at openllet.core.rules.rete.AlphaNetwork.activateIndividual(AlphaNetwork.java:133)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at openllet.core.rules.rete.AlphaNetwork.activateAll(AlphaNetwork.java:119)
        at openllet.core.rules.rete.Interpreter.run(Interpreter.java:60)
        at openllet.core.rules.ContinuousRulesStrategy.applyRete(ContinuousRulesStrategy.java:145)
        at openllet.core.rules.ContinuousRulesStrategy.complete(ContinuousRulesStrategy.java:224)
        at openllet.core.boxes.abox.ABoxImpl.lambda$isConsistent$12(ABoxImpl.java:1417)
        at openllet.core.utils.Timers.execute(Timers.java:118)
        at openllet.core.boxes.abox.ABoxImpl.isConsistent(ABoxImpl.java:1417)
        at openllet.core.boxes.abox.ABoxImpl.isConsistent(ABoxImpl.java:1269)
        at openllet.core.KnowledgeBaseImpl.consistency(KnowledgeBaseImpl.java:1802)
        at openllet.core.KnowledgeBaseImpl.isConsistent(KnowledgeBaseImpl.java:1877)
        at openllet.core.KnowledgeBaseImplFullSync.isConsistent(KnowledgeBaseImplFullSync.java:403)
        at openllet.owlapi.PelletReasoner.isConsistent(PelletReasoner.java:1032)
        at de.athalis.owl.PrunedNode.printProcesses(PrunedNode.java:77)
        at de.athalis.owl.PrunedNode.main(PrunedNode.java:31)
```

Simply changing the corresponding line from `return _wmeProvider.getNode(wme, token).getTerm().equals(_tokenProvider.getNode(wme, token).getTerm());` to `return java.util.Objects.equals(_wmeProvider.getNode(wme, token).getTerm(), _tokenProvider.getNode(wme, token).getTerm());` seems like an easy fix. I applied that change locally and didn't discover any drawbacks yet.

However I can't tell whether that is just fixing a symptom that is causing my other issues (in particular #38 as that happens in the same region). It might be that it is unexpected to have an anonymous literal with no value at this place?..

Note that this is independent of whether I set `OpenlletOptions.TRACK_BRANCH_EFFECTS = true;` or not.

**Comment by Locke** [comment]
Resolved with #60
