### ISSUE TITLE
Unsupported rule Rule 

### ISSUE THREAD

**Issue by amin101** [Galigator/openllet#67]
I am using openllet 2.6.3 and owlapi 5.1.19 .  have some swrl rules created by protege :

`Patient(?patient) ^ Has_EDSS(?patient, ?edss) ^ swrlb:lessThan(?edss, 7777) ->Should_be_used(?patient,:_Treadmill_walking)`

but i get error:

```
Exception in thread "main" openllet.atom.OpenError: Unsupported rule Rule([Patient(?patient), Has_EDSS(?patient,?edss), lessThan([?edss, "7777"^^integer])] => [Should_be_used(?patient,_Treadmill_walking)])
	at openllet.core.rules.ContinuousRulesStrategy.complete(ContinuousRulesStrategy.java:208)


Caused by: java.lang.UnsupportedOperationException: Builtin using unsafe variables: [lessThan([?edss, "7777"^^integer])]
	at openllet.core.rules.rete.Compiler.compile(Compiler.java:235)
	at openllet.core.rules.ContinuousRulesStrategy.complete(ContinuousRulesStrategy.java:204)
```

also I open the question in [stackoverflow ](https://stackoverflow.com/questions/70307955/openlletunsupported-rule-rule)

**Comment by Galigator** [comment]
This is strange because there is a test case in https://github.com/Galigator/openllet/blob/2.6.3/module-owlapi/src/test/java/openllet/pellet/owlapi/test/TestBasic.java#L506 for the _lessThan_ swrlb predicat.  Could you give more detail about your ontology ? A sub-ontology that just throw the exception could be nice.

**Comment by amin101** [comment]
This error was due to the definition of a object property of the same name with data property.removing the object property and modifying swrl rule resolved the issue
